### ISSUE TITLE
Possible compilation issue of genbankr on macOS

### ISSUE THREAD

**Issue by michaelgruenstaeudl** [gmbecker/genbankr#13]
Hi Gabriel,
recently I was [informed by CRAN](https://cran.r-project.org/web/checks/check_results_PACVr.html) that genbankr were not available (or does not compile) on macOS, yet continues to be available for Linux. I am maintaining an R package on CRAN called [PACVr](https://cran.r-project.org/web/packages/PACVr/index.html) which has genbankr as a dependency.

Hence, I suspect that there is a compilation issue with genbankr specifically on macOS. Could you please test your package on macOS. I would like to continue listing genbankr as a dependency of my package.
Thanks, Michael

**Comment by gmbecker** [comment]
Hi @michaelgruenstaeudl 

Glad to hear you're finding genbankr useful!

I'm not sure why you would have gotten this, genbankr is a Bioconductor package and is currently succeeding in across all tested platforms  in their build system for both the release and devel versions of genbankr. 

It may be an intermittent failure somehow but if it persists I'll reach out to the Bioc build people and see if they have any idea whats going on.

**Comment by gmbecker** [comment]
Closing this as the package is still on CRAN and still depends on genbankr
