### ISSUE TITLE
regex in LOCUS parsing detects literal t.

### ISSUE THREAD

**Issue by sbthandras** [gmbecker/genbankr#17]
in R/genbankReader.R: line 171-175
the spl =strsplit ... line should only contain a single tab I think.

`readLocus = function(line) {
    ## missing strip fieldname?
    spl = strsplit(line, "[\\t]+", line)[[1]]
    spl
}`

**Comment by gmbecker** [comment]
Apologies this took so long to get to, The issue appears to be that the `\\t` should be `\t`. Changing it as such fixes #18

I will do a bit more testing and try to push this at least to bioc devel.

**Comment by gmbecker** [comment]
Fix for this has been pushed both to github and bioc git repos. Closing this issue, please have a look and reopen if it doesn't work for you.

**Comment by sbthandras** [comment]
> Fix for this has been pushed both to github and bioc git repos. Closing this issue, please have a look and reopen if it doesn't work for you.

Thanks for the fix, no problem about the delay, I've found a workaround in the meantime. I've tested it with the file that originally produced the error and it works now !
